databases:
  - name: rails_auth_app
    databaseName: rails_auth_app
    user: funxxfun
    region: singapore

services:
  - type: web
    name: rails_auth_app
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: rails_auth_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false