development:
  auth0_domain: dev-40o731wzgfxo3z3h.us.auth0.com
  auth0_client_id: MfdiRQkgEKpfpY1aUAJRh0gRtBtqcwXL
  auth0_client_secret: 2CgaZgA4Aj02igWMPjlaPMoCNsQmbivRfLXM1WR9Q9_IxMkOJ7O5YMoXb-XmrmVh
